spring.datasource.url=jdbc:postgresql://localhost:5432/lunario_db
spring.datasource.username=lunario_user
spring.datasource.password=password123
# Faz o Hibernate criar as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update